title: "Tamara Dragutinovic â€” Legal & Fintech Writer"
description: "Content on fintech, law, and regulation."
theme: minima
plugins:
  - jekyll-seo-tag
header_pages:
  - about.md
  - contact.md
  

# Optional navigation (for themes that support it)
# header_pages:
#   - about.md
#   - services.md
#   - contact.md

