title: "Tamara Dragutinovic - Legal & Fintech Writer"
description: "Content on fintech, law, and regulation."
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-feed
header_pages:
  - about.md
  - contact.md
  - privacy/index.md

  

# Optional navigation (for themes that support it)
# header_pages:
#   - about.md
#   - services.md
#   - contact.md

url: "https://anapurna12.github.io"
baseurl: "/TamaraDragutinovic"




